#!/bin/sh

# Core extensions
alias ls="ls -A"
alias ll="ls -lh"

# Git aliases
alias g="git"
alias gs="git status"
alias ga="git add"
alias gc="git duet-commit -v"
alias gd="git diff"
alias gds="git diff --staged"
alias gl="git log"
alias chead="git commit --amend -CHEAD"

# Utilities
alias eda="emacs --daemon"
alias e="emacsclient -t"
alias ek="emacsclient -e '(kill-emacs)'"
